baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

defaultContentLanguage = 'en'

# theme as module
[module]
replacements = "github.com/Sped0n/twelve -> ../.." # deploy with local dir  WARN: delete this line if you want to deploy with git
[[module.imports]]
path = "github.com/Sped0n/twelve" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!
